apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: topic-from-cfk
  namespace: confluent
spec:
  replicas: 3 # Topic replication factor must be 3
  partitionCount: 3
  configs:
    cleanup.policy: "compact"
  kafkaRest:
    endpoint: <CCLOUD_API_REST_ENDPOINT> 
    kafkaClusterID: <CCLOUD_CLUSTER_ID>
    authentication:
      type: bearer
      bearer:
        secretRef: ccloud-credentials