apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-schema-registry:7.3.0
    init: confluentinc/confluent-init-container:2.5.0
  enableSchemaExporter: true
  passwordEncoder:
    secretRef: ccloud-sr-secret
  dependencies:
    kafka:
      bootstrapEndpoint: kafka:9071