apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: invalid-topic
  namespace: confluent
spec:
  replicas: 1
  partitionCount: 15
  configs:
    cleanup.policy: "delete"
  kafkaRestClassRef:
    name: kafkarest