apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: pageviews
  namespace: source
spec:
  replicas: 1
  partitionCount: 1
  kafkaClusterRef:
    name: kafka
    namespace: source