apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: source-topic
  namespace: source
spec:
  replicas: 1
  partitionCount: 1
  configs:
    cleanup.policy: "delete"
  kafkaRestClassRef:
    name: source-kafka-rest