apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: c3-ingress
  namespace: confluent  
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: controlcenter-0-internal
            port:
              number: 9021
      