apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: kakfatopicpartitions
spec:
  crd:
    spec:
      names:
        kind: KakfaTopicPartitions
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package topics 

        violation[{"msg": "KafkaTopic partitionCount must be less than the maximum allowed number of partitions (set via the 'maxPartitions' parameter)."}] {
        input.review.object.spec.partitionCount > input.parameters.maxPartitions
        }
  