apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: pageviewssr
  namespace: confluent
spec:
  class: "io.confluent.kafka.connect.datagen.DatagenConnector"
  taskMax: 2
  connectClusterRef:
    name: connect
  configs:
    kafka.topic: "pageviews_sr" 
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    value.converter: "io.confluent.connect.avro.AvroConverter" 
    value.converter.schemas.enable: "true"
    value.converter.schema.registry.url: <SR_URL>
    value.converter.schema.registry.basic.auth.user.info: <SR_APP_KEY:SR_APP_SECRET>
    value.converter.schema.registry.basic.auth.credentials.source: USER_INFO
    max.interval: "100"
    iterations: "10000000"
    schema.string: "{\"type\": \"record\", \"namespace\": \"datagen\", \"name\": \"pageviews\", \"fields\": [{\"type\": {\"type\": \"long\", \"format_as_time\": \"unix_long\", \"arg.properties\": {\"iteration\": {\"start\": 1, \"step\": 10}}}, \"name\": \"viewtime\"}, {\"type\": {\"type\": \"string\", \"arg.properties\": {\"regex\": \"User_[1-9]{0,1}\"}}, \"name\": \"userid\"}, {\"type\": {\"type\": \"string\", \"arg.properties\": {\"regex\": \"Page_[1-9][0-9]?\"}}, \"name\": \"pageid\"}]}"
    schema.keyfield: "pageid"
    

 