apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: kafkarest
  namespace: confluent
spec:
  kafkaClusterRef:
    name: kafka
  kafkaRest:
    endpoint: http://kafka.confluent.svc.cluster.local:8090